# Site settings
title: 
description: "Proactively secure web application development using the BCHS (OpenBSD, C, httpd, SQLite) software stack."

# User settings
username: Applied OpenBSD
user_description: Join us in our public chatroom public@conference.appliedopenbsd.com (UTC / Zulu +10)

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
