# Site settings
title: XMPP Partners
description: Standards-based, encrypted XMPP protocol messaging for low bandwidth, high latency and intermittent or disconnected communication networks.

# User settings
username: XMPP Partners
user_description: We're serious about secure, real time XMPP protocol messaging and presence communication in the toughest network environments.</a>
user_title: Secure machine-to-machine XMPP protocol messaging for low bandwidth, high latency and intermittent communication networks. 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
